#+title:	Master of Ceremonies
#+author:	Positron
#+email:	contact@positron.solutions

* Tools for Display & Presenting
This package is still pre-1.0.  The ~mc-focus~ command is super useful!  Therefore, it is made available in this very rough state.

- display and annotate a region of text fullscreen for screen capture and
  playback with ~mc-focus~
- set resolution with ~mc-resolution~
- subtle cursor mode ~mc-subtle-cursor-mode~
- hide cursor mode ~mc-hide-cursor-mode~
- no messages ~mc-quiet-mode~

Subscribe to [[https://www.youtube.com/@Positron-gv7do][Positron's YouTube channel]] to catch updates on when it's added to package archives and more information about how to use it.
** Installation
#+begin_src elisp
   ;; package-vc
   (package-vc-install
    '(master-of-ceremonies
      :url "https://github.com/positron-solutions/master-of-ceremonies.git"))

   ;; using elpaca's with explicit recipe
   (use-package master-of-ceremonies
     :elpaca (master-of-ceremonies 
              :host github
              :repo "positron-solutions/master-of-ceremonies"))

   ;; straight with explicit recipe
   (use-package master-of-ceremonies
     :straight (master-of-ceremonies 
                :type git :host github
                :repo "positron-solutions/master-of-ceremonies"))

   ;; or use manual load-path & require, you brave yak shaver
#+end_src
** Planned Features
MC was developed alongside [[https://github.com/positron-solutions/dslide][dslide]] when dslide was still called Macro Slides.  Features where Dslide can benefit from the out-of-the-box behavior will be integrated into dslide.  Features thave have strong standalone value *and* are not tedious to integrate with dslide via hooks can live in MC.

*** Multi-Setting Control
It can be rather annoying when switching between multiple sets of coherent
settings.  For exmaple, it is tedious to change from a live demonstration style
setup to a full-screen projector slide show style setup.  One set of hooks
cannot do the job.
